logging:
  level:
    .: error
    org.springframework: info
    website.marcioheleno: info

server:
  compression:
    enabled: true

spring:
  profiles:
    active:
      - test
#  main:
#    banner-mode: console
  jpa:
    open-in-view: false

security:
  oauth2:
    client:
      client-id: frontAjax
      client-secret: frontAjax123

jwt:
  secret: MY-JWT-SECRET
  duration: 86400


---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      path: /h2-console
  jpa:
    show-sql: true
    generate-ddl: true

---

spring:
  profiles: stage
  datasource:
    url: jdbc:postgresql://localhost:5432/api-ajax
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        formatSql: true
        jdbc:
          lob:
            non-contextual-creation: true
    hibernate:
      ddlAuto: none

---

spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5432/api-ajax
    username: postgres
    password: 1234
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            script:
              action: create
              create-target: "create.sql"
      hibernate:
        hbm2ddl:
          delimiter: ;
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none

---


spring:
  profiles: prod
  datasource:
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        formatSql: false

security:
  oauth2:
    client:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}

jwt:
  secret: ${JWT_SECRET}
  duration: ${JWT_DURATION}