logging:
  level:
    .: error
    org.springframework: info
    website.marcioheleno: error

spring:
  profiles:
    active:
      - test
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      path: /h2-console
server:
  compression:
    enabled: true


---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/api-ajax
    username: postgres
    password: 1234567
  jpa:
    properties:
      hibernate:
        formatSql: true
        jdbc:
          lob:
            non-contextual-creation: true
    hibernate:
      ddlAuto: none

---

spring:
  profiles: dev2
  datasource:
    url: jdbc:postgresql://localhost:5432/api-ajax
    username: postgres
    password: 1234567
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
          script:
            action: create
            create-target: create.sql
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: true
        formatSql: true
        jdbc:
          lob:
            non-contextual-creation: true

    hibernate:
      hbm2ddl:
        delimiter: ";"
      ddlAuto: none

---

spring:
  profiles: prod
  datasource:
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        formatSql: false
